version: '1.0'
services:  
  api:    
    build: ./api    
    container_name: api_backend    
    ports:      
      - '4000:4000'
    expose:
    - '7070'
    links:
      - mongodb
    restart: unless-stopped  
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:     
      - ./api:/app      
      - /app/node_modules
    depends_on:
      - mongodb
  front:    
    build: ./next    
    container_name: frontend    
    ports:      
      - '3000:3000'
    restart: unless-stopped   
    volumes:     
      - ./next:/app      
      - /app/node_modules
  mongodb:
    image:  mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb